### ISSUE TITLE
Fix dependencies

### ISSUE THREAD

**Issue by seroukhov** [pip-webui/pip-webui-settings#3]
Add external dependencies must be defined at the main module level. Add internal dependencies must be set explicitely. The following statement is incorrect. It shall now happen if dependencies are defined correctly. User shall add just pipUserSettings.Sessions reference.

Если вы хотите подключить отдельно страницу Active sessions необходимо добавить модули:
'pipUserSettings.Sessions',
'pipSettings.Service',
'pipSettings.Page'

**Comment by KateNegrienko** [comment]
complete
